coffee_site/coffee_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import logout

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from general.views import CoffeeListView, CoffeeCreateView, CoffeeDetailView
from general.views import CoffeeBagListView, CoffeeBagDetailView
from general.views import roaster_list_view, RoasterDetailView, UserRoasterListView
from general.views import store_list_view, StoreDetailView, UserStoreListView

from coffee_bag.views import PurchasedCoffeeBagDetailView
from coffee_bag.views import PurchasedCoffeeBagListView
from coffee_bag.views import UserPurchasedCoffeeBagListView

from coffee_ratio.views import PreparationListView, MyPreparationListView
from coffee_ratio.views import PreparationDetailView

media_root = getattr(settings, 'MEDIA_ROOT', '/media')    


urlpatterns = patterns('',
                       # Examples:
                           
                       #url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
                       #url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
                       #url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
                       #url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
                       #url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
                       #url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
                       #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$','django.contrib.auth.views.password_reset_confirm',name='password_reset_confirm'),
                       #url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),  
                       
                       # Main page
                       url(r'^$', 'general.views.home', name='home'),
                       
                       # Main page when logged in
                       url(r'login/$', 'general.views.login_user'),
                       url(r'logout/$', 'general.views.logout'),
                       
                       url('^register/$', CreateView.as_view(template_name='signup.html', form_class=UserCreationForm, success_url='/')),
                       
                       url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': media_root}),
                       
                       # View a list of roasters
                       url(r'^roasters/$', 
                           'general.views.roaster_list_view', 
                           name="roaster_list_view"),

                       # View a list of roasters
                       url(r'^coffeebag_by_roaster_json/$', 
                           'general.views.coffeebag_by_roaster_view_json', 
                           name="coffeebag_by_roaster_view_json"),
                       
                       # View details for roaster by primary key
                       url(r'^roaster/(?P<pk>\d+)/$', 
                           view=RoasterDetailView.as_view(),
                           name="roasterdetail"),
                       
                       # View a list of roasters for a user
                       url(r'^myroasters/$', 
                           login_required(UserRoasterListView.as_view()),
                           name="myroasterlist"),
                       
                       # Add a roaster to current user's roaster list                     
                       url(r'^adduserroaster/$', 
                           view='general.views.add_user_roaster',
                           name="add_user_roaster"),
                       
                       # Remove a roaster to current user's roaster list                     
                       url(r'^removeuserroaster/$', 
                           view='general.views.remove_user_roaster',
                           name="remove_user_roaster"),

                       # Rate a roaster to current user's roaster list
                       url(r'^rateuserroaster/$', 
                           view='general.views.rate_user_roaster',
                           name="rate_user_roaster"),
                       
                       # View a list of stores
                       url(r'^stores/$', 
                           'general.views.store_list_view', 
                           name="store_list_view"),
                       
                       # View details for store by primary key
                       url(r'^store/(?P<pk>\d+)/$', 
                           view=StoreDetailView.as_view(),
                           name="storedetail"),
                       
                       # View a list of stores for a user
                       url(r'^mystores/$', 
                           login_required(UserStoreListView.as_view()),
                           name="mystorelist"),
                       
                       # Add a store to current user's store list                     
                       url(r'^adduserstore/$', 
                           view='general.views.add_user_store',
                           name="add_user_store"),
                       
                       # Remove a store to current user's store list                     
                       url(r'^removeuserstore/$', 
                           view='general.views.remove_user_store',
                           name="remove_user_store"),

                       # Rate a store to current user's store list
                       url(r'^rateuserstore/$', 
                           view='general.views.rate_user_store',
                           name="rate_user_store"),
                       
                       # View detail for a coffee
                       url(r'^coffee/(?P<pk>\d+)/$', 
                           view=CoffeeDetailView.as_view(),
                           name="coffeedetail"),
                       
                       # View detail for a coffee bag
                       url(r'^coffeebag/(?P<pk>\d+)/$', 
                           view=CoffeeBagDetailView.as_view(),
                           name="coffeebagdetail"),
                       
                       # View detail for a purchased coffee bag
                       url(r'^purchcoffeebag/(?P<pk>\d+)/$', 
                           view=PurchasedCoffeeBagDetailView.as_view(),
                           name="purchcoffeebagdetail"),

                       # View list of purchased coffee bags
                       url(r'^purchased_coffees/$', 
                           view=PurchasedCoffeeBagListView.as_view(),
                           name="purchcoffeebaglist"),

                       # View list of purchased coffee bags for a particular user
                       url(r'^purchased_coffees/([A-Za-z]+[\w-]*)/$', 
                           view=UserPurchasedCoffeeBagListView.as_view(),
                           name="userpurchcoffeebaglist"),

                       # Create a new purchased coffee bags
                       url(r'^addpurchcoffeebag/$', 
                           view='coffee_bag.views.purchased_coffee_bag_create_view',
                           name="purchcoffeebagcreate"),
                       
                       # Create a new coffee 
                       url(r'^addcoffee/$', 
                           view=CoffeeCreateView.as_view(),
                           name="coffeecreate"),

                       # View a list of coffees
                       url(r'^coffees/$', 
                           view=CoffeeListView.as_view(),
                           name="coffeelist"),

                       # View a list of coffee bags
                       url(r'^coffeebags/$', 
                           view=CoffeeBagListView.as_view(),
                           name="coffeebaglist"),

                       # View a list of preparations
                       url(r'^preparations/$', 
                           view=PreparationListView.as_view(),
                           name="preparationlist"),

                       # View a list of preparations
                       url(r'^mypreparations/$', 
                           view=MyPreparationListView.as_view(),
                           name="mypreparationlist"),
                      
                       # Create a new purchased coffee bags
                       url(r'^addpreparation/$', 
                           view='coffee_ratio.views.preparation_create_view',
                           name="preparationcreateview"),

                       # View detail for a preparation
                       url(r'^preparation/(?P<pk>\d+)/$', 
                           view=PreparationDetailView.as_view(),
                           name="preparationdetail"),
                       
                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       
                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       # Only for devel!!!
                       # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
                       
                       )

coffee_site/coffee_bag/models.py
from django.db import models
from django import forms
from django.conf import settings

from sorl.thumbnail import ImageField

from djangoratings.fields import RatingField

from general.models import Store, CoffeeBag, CoffeeBagImage

    
class PurchasedCoffeeBag(models.Model):
    """DB model for a purchased coffee bag.
    
    Has relationships to a user, store, and coffee bag.
    
    """
    
    date_purch = models.DateField('Purchase Date', blank=True)
        
    rating = RatingField(range=5, weight=5, can_change_vote=True, allow_delete=True, allow_anonymous=False)

    notes = models.TextField(blank=True, null=True)    

    thumb = models.ForeignKey(CoffeeBagImage, blank=True, null=True)

    # Better way to specify the user than the User object
    user = models.ManyToManyField(settings.AUTH_USER_MODEL)
    store = models.ForeignKey(Store, blank=False, null=False)
    coffeebag = models.ForeignKey(CoffeeBag, blank=False, null=False)
    
    def __unicode__(self):
        return "%s, %s, %s" % (self.coffeebag.coffee.name, 
                               self.coffeebag.roaster.name,
                               self.store.name)

    class Meta:
        # Default ordering - chronological by purchase date
        ordering = ["-date_purch"]

        permissions = (('view_purch_coffee_bag', 'View purchased coffee bag'),)

def make_custom_datefield(f):
    """Change format of date fields in form.
    
    Should move to a utilities module.
    
    """
    
    formfield = f.formfield()
    if isinstance(f, models.DateField):
        formfield.widget.format = '%Y-%m-%d'
        formfield.widget.attrs.update({'class': 'datePicker', 'readonly': 'true'})
    return formfield

class PurchasedCoffeeBagForm(forms.ModelForm):
    """Form model for purchased coffee bags.
    
    """

    # Change format of date fields in form.
    formfield_callback = make_custom_datefield
    
    class Meta:
        model = PurchasedCoffeeBag
        
        # Logged in user will add a purchased coffee bag
        # so in form the user field should not be displayed.
        exclude = ('user', 'coffeebag')

coffee_site/coffee_bag/forms.py
from django import forms
from django.db import models

import selectable.forms

from general.models import Coffee, CoffeeBag, Store, Roaster
from .models import PurchasedCoffeeBag

def make_custom_datefield(f):
    """Change the format of the date in form fields.
    
    """
    
    formfield = f.formfield()

    if isinstance(f, models.DateField):
        formfield.widget.format = '%Y-%m-%d'
        formfield.widget.attrs.update({'class': 'datePicker', 'readonly': 'true'})

    return formfield

class PurchasedCoffeeBagForm(forms.ModelForm):

    roaster = forms.ModelChoiceField(queryset=Roaster.objects.all())
    coffeebag = forms.ModelChoiceField(queryset=CoffeeBag.objects.none(), required=False)
    notes = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols':150}))

    # change the format of the date fields
    formfield_callback = make_custom_datefield
    
    def __init__(self, *args, **kwargs):

        super(PurchasedCoffeeBagForm, self).__init__(*args, **kwargs)

        roasters = Roaster.objects.all()

        if len(roasters) == 1:
            self.fields['roaster'].initial = roasters[0].pk

        roaster_id = self.fields['roaster'].initial or \
            self.initial.get('roaster') or \
            self._raw_value('roaster')
        
        if roaster_id:
            # roaster is known. Now I can display the matching coffee bags.
            coffeebags = CoffeeBag.objects.filter(roaster__id=roaster_id)
            self.fields['coffeebag'].queryset = coffeebags

            if len(coffeebags) == 1:
                self.fields['coffeebag'].initial = coffeebags[0].pk

    class Meta:
        model = PurchasedCoffeeBag
        
        fields = ('date_purch', 'roaster', 'coffeebag', 'store', 'notes')

        exclude = ('user', )

coffee_site/general/forms.py
from django import forms
from django.db import models

import selectable.forms

from .models import Coffee, CoffeeBag, Store, Roaster
from .lookups import RoasterLookup

def make_custom_datefield(f):
    """Change the format of the date in form fields.
    
    """
    
    formfield = f.formfield()

    if isinstance(f, models.DateField):
        formfield.widget.format = '%Y-%m-%d'
        formfield.widget.attrs.update({'class': 'datePicker', 'readonly': 'true'})

    return formfield

class CoffeeForm(forms.ModelForm):
    """Form model for adding new coffees.
    
    """
    
    # change the format of the date fields
    formfield_callback = make_custom_datefield
    
    class Meta:
        model = Coffee
        
class CoffeeBagForm(forms.ModelForm):
    """Form model for adding new coffees.
    
    """
    
    # change the format of the date fields
    formfield_callback = make_custom_datefield

    autocomplete = forms.CharField(label='Roaster',
                                   widget=selectable.forms.AutoCompleteWidget(RoasterLookup),
                                   required=False)
    
    class Meta:
        model = CoffeeBag
        
        exclude = ('thumb',)

class StoreForm(forms.ModelForm):
    """Form model for adding new stores.
    
    """
        
    class Meta:
        model = Store

class RoasterForm(forms.ModelForm):
    """Form model for adding new stores.
    
    """

    autocomplete = forms.CharField(
        label='Type the name of a roaster',
        widget=selectable.forms.AutoCompleteWidget(RoasterLookup),
        required=False,
    )    

    
    class Meta:
        model = Roaster

        fields = ('autocomplete', 'address', 'city', 'state', 'zipcode', 'website', 
                  'phone', 'fbook', 'twitter', 'gplus')
        exclude = ('lgt', 'lat',)

class RoasterLookupForm(forms.Form):

    roaster = forms.ModelChoiceField(queryset=Roaster.objects.all())
    coffeebag = forms.ModelChoiceField(queryset=CoffeeBag.objects.none(), required=False)
    
    def __init__(self, *args, **kwargs):

        super(RoasterLookupForm, self).__init__(*args, **kwargs)
        forms.Form.__init__(self, *args, **kwargs)

        roasters = Roaster.objects.all()

        if len(roasters) == 1:
            self.fields['roaster'].initial = roasters[0].pk

        roaster_id = self.fields['roaster'].initial or \
            self.initial.get('roaster') or \
            self._raw_value('roaster')
        
        if roaster_id:
            # roaster is known. Now I can display the matching coffee bags.
            coffeebags = CoffeeBag.objects.filter(roaster__id=roaster_id)
            self.fields['coffeebag'].queryset = coffeebags

            if len(coffeebags) == 1:
                self.fields['coffeebag'].initial = coffeebags[0].pk

coffee_site/templates/coffee_journal/coffee/coffee_carousel.html
<!-- Testing code for implementing a carousel view of images using Bootstrap -->

{% extends "base.html" %}

{% block title %}Coffee's in Journal{% endblock %}

{% block loggedinstatus %}Logged in as <a href="#" class="navbar-link">{{ user.username }}</a> (<a href="/logout/" class="navbar-link">Logout</a>){% endblock %}

{% block content %}

<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
      <img src="{{ STATIC_URL }}img/1.jpg" height=250>
      <div class="carousel-caption">
        <h4>First Thumbnail label</h4>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      </div>
    </div>

    <div class="item">
      <img src="{{ STATIC_URL }}img/2.jpg" height=250>
      <div class="carousel-caption">
        <h4>Second Thumbnail label</h4>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      </div>
    </div>
    
    <div class="item">
      <img src="{{ STATIC_URL }}img/3.jpg" height=250>
      <div class="carousel-caption">
        <h4>Third Thumbnail label</h4>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      </div>
    </div>

    <div class="item">
      <img src="{{ STATIC_URL }}img/4.jpg" height=250>
      <div class="carousel-caption">
        <h4>Fourth Thumbnail label</h4>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      </div>
    </div>

    <div class="item">
      <img src="{{ STATIC_URL }}img/5.jpg" height=250>
      <div class="carousel-caption">
        <h4>Fifth Thumbnail label</h4>
        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      </div>
    </div>
  
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>


{% endblock %}

coffee_site/templates/coffee_journal/coffee/coffee_create.html
{% extends "base.html" %}

{% block title %}Add a Coffee{% endblock %}

{% block loggedinstatus %}Logged in as <a href="#" class="navbar-link">{{ user.username }}</a> (<a href="/logout/" class="navbar-link">Logout</a>){% endblock %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="span4 offset4">
<h1>Add A Coffee</h1>
<form action="/addcoffee/" method="POST">{% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Save" />
</form>      
</div>

{% endblock %}

{% block scripts %}
<script src="{{ STATIC_URL }}/js/jquery-1.9.1.js"></script>
<script src="{{ STATIC_URL }}/js/jquery-ui-1.10.3.js"></script>
<script>	
  jQuery(function($){
  //all jQuery code which uses $ needs to be inside here
  $( ".datePicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
  });
</script>

{% endblock %}

</section> <!-- #content -->  

coffee_site/templates/coffee_journal/coffee/coffee_detail.html
{% extends "base.html" %}

{% block otherstyles %}
<link rel="stylesheet" href="{{ STATIC_URL }}/css/rating.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}/css/coffeebag.css" />

{% endblock %}

{% block title %}Coffee Detail: {{ coffee.name }} {% endblock %}

{% block loggedinstatus %}Logged in as <a href="#" class="navbar-link">{{ user.username }}</a> (<a href="/logout/" class="navbar-link">Logout</a>){% endblock %}

{% block content %}

<div class="span12">
  
  <div class="coffeetitle">
    <div class="coffeetitle_head">
      <h1>{{ coffee.name }}</h1>
    </div>
  </div>
  
  <div class="row-fluid">
    
    <div class="span4">
      <div class="item">
	<div class="item_head">
	  <h2>Coffee</h2>
	</div>
	<ul>
	  <li>Finca: {{ coffee.finca }}</li>
	  <li>Grower: {{ coffee.grower }}</li>
	  <li>Varietal: {{ coffee.varietal }}</li>
	  <li>Altitude: {{ coffee.altitude }}m</li>
	</ul>
      </div>
    </div>  
    
    <div class="span8">
      <div class="item">
	<div class="item_head">
	  <h2>Notes</h2>
	</div>
	<pre>{{ coffee.notes }}</pre>
      </div>
    </div>
  
  </div> <!--- end row --->
  
</div>

{% endblock %}

coffee_site/templates/coffee_journal/coffee/coffee_list.html
{% extends "base.html" %}

{% block title %}<title>My Coffee Journal</title>{% endblock %}

{% block otherstyles %}
<link rel="stylesheet" href="{{ STATIC_URL }}/css/rating.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}/css/coffeebag.css" />
{% endblock %}

{% block loggedinstatus %}Logged in as <a href="#" class="navbar-link">{{ user.username }}</a> (<a href="/logout/" class="navbar-link">Logout</a>){% endblock %}

{% block content %}

<h1>{{ user.first_name }} {{ user.last_name }}'s Coffees</h1>

{% if coffee_list %}

{% for coffee in coffee_list %}

<div class="row-fluid">
  <div class="span10">
    <div class="item">
      <div class="item_head">
	<h2>{{ coffee.name }}</h2>
      </div>
      Purchased on {{ coffee.date_purch }}
      <!-- <img src="{{ STATIC_URL }}/img/{{ coffee.id }}.jpg" width=100> -->
      <a class="btn" href="/coffee/{{ coffee.id }}/">View details &raquo;</a>
    </div><!--/span-->
  </div>
</div>

{% endfor %}

{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    
    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>
{% endif %}



{% else %}
<div class="row-fluid">
  <div class="span8">
    <p>No coffee available.</p>
  </div><!--/span-->
</div>
{% endif %}

{% endblock %}

coffee_site/templates/coffee_journal/coffee/coffee_search.html
{% extends "base.html" %}

{% block title %}Coffee's in Journal{% endblock %}

{% block otherstyles %}
<link rel="stylesheet" href="{{ STATIC_URL }}/css/rating.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}/css/coffeebag.css" />
{% endblock %}

{% block loggedinstatus %}Logged in as <a href="#" class="navbar-link">{{ user.username }}</a> (<a href="/logout/" class="navbar-link">Logout</a>){% endblock %}

{% block content %}


<!-- <div class="span10"> -->
<div class="row-fluid">
  
  <div class="span10">

    <div class="item">
      <div class="item_head">
	<h2>Search</h2>
      </div>

      <form action="/search/" method="GET">
	<input type="text" name="q" />
	<button type="submit">Search</button>
      </form>
      
    </div><!--/span-->
  </div>
</div>


{% endblock %}

coffee_site/templates/coffee_journal/coffee/coffeebag_detail.html
{% extends "base.html" %}

{% block otherstyles %}
<link rel="stylesheet" href="{{ STATIC_URL }}/css/rating.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}/css/coffeebag.css" />

{% endblock %}

{% block title %}Coffee Detail: {{ coffeebag.name }} {% endblock %}

{% block loggedinstatus %}Logged in as <a href="#" class="navbar-link">{{ user.username }}</a> (<a href="/logout/" class="navbar-link">Logout</a>){% endblock %}

{% block content %}

<div class="span12">

  <div class="coffeetitle">
    <div class="coffeetitle_head">
      <h1>{{ coffeebag.coffee.name }}</h1>
    </div>
  </div>
  
  <div class="row-fluid">
    
    <div class="span4">
      <div class="item">
	<div class="item_head">
	  <h2>Coffee</h2>
	</div>
	<ul>
	  <li>Finca: {{ coffeebag.coffee.finca }}</li>
	  <li>Grower: {{ coffeebag.coffee.grower }}</li>
	  <li>Varietal: {{ coffeebag.coffee.varietal }}</li>
	  <li>Altitude: {{ coffeebag.coffee.altitude }}m</li>
	</ul>
      </div>
    </div>
    
    <div class="span4">
      <div class="item">
	<div class="item_head">
	  <h2>Roaster</h2>
	</div>
	<!-- <img src="{{ STATIC_URL }}/img/{{ coffeebag.id }}.jpg" width="150"><br /> -->
	
	<ul>
	  <li>Name: {{ coffeebag.roaster.name }}</li>
	  <li>Date: {{ coffeebag.date_roast }}</li>
	</ul>
      </div>
    </div>
  </div>
  
  <div class="row-fluid">
    
    <div class="item">
      <div class="item_head">
	<h2>Notes</h2>
      </div>
      <pre>{{ coffeebag.notes }}</pre>
    </div>
  </div>

</div>

{% endblock %}

coffee_site/templates/coffee_journal/coffee/purchasedcoffeebag_create.html
{% extends "base.html" %}

{% block title %}<title>Add a Coffee</title>{% endblock %}

{% block content %}

<h1>Add A Coffee</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'purchcoffeebagcreate' %}" method="post">{% csrf_token %}

  <div class="row">
    
    <div class="span9">
      
      {% if form.errors %}
      <p style="color: red;">
	Please correct the error{{ purchcoffeebagform.errors|pluralize }} below.
      </p>
      {% endif %}
    </div>
  </div>
  
  <div class="row">

    <div class="span3">
      <div class="item">
	
	<div class="field">
	  <label for="id_date_purch">Purchase Date:</label> 
          {{ purchcoffeebagform.date_purch }}
	</div>
	
	<div class="field">
	  <label for="id_store">Store:</label> 
          {{ purchcoffeebagform.store }}
	</div>
	
      </div>
    </div>
    
    <div class="span3">
      <div class="item">
	
	<div class="field">
	  <label for="id_roaster">Roaster:</label>
          {{ purchcoffeebagform.roaster }}
	</div>
	
	<div class="field">
	  <label for="id_coffeebag">Coffee Bag:</label>
          {{ purchcoffeebagform.coffeebag }}
	</div>
	
      </div>
    </div>
    
  </div>
  
  <div class="row">
    
    <div class="span6">
	
	<div class="field">
	  <label for="id_notes">Notes:</label> 
          {{ purchcoffeebagform.notes }}
	</div>
	
	<input type="submit" value="Save" />
    </div>
  </div>
  
</form>      

{% endblock %}

{% block script %}
<script src="{{ STATIC_URL }}js/jquery-1.9.1.js"></script>  
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>  
<script src="{{ STATIC_URL }}/js/jquery-ui-1.10.3.js"></script>
<script src="{{ STATIC_URL }}/js/general/roaster_lookup.js"></script>

<script>	
  jQuery(function($){
  //all jQuery code which uses $ needs to be inside here
  $( ".datePicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
  });
</script>

{% endblock %}

</section> <!-- #content -->  